[versions]
kotlin-jvm = "2.3.10"
loom = "1.15-SNAPSHOT"
publishing = "1.1.0"
blossom = "1.3.2"
ksp = "2.3.6"
fletchingtable = "0.1.0-alpha.22"
spotless = "8.2.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
loom-remap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "loom" }
publishing = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publishing" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
fletchingtable-fabric = { id = "dev.kikugie.fletching-table.fabric", version.ref = "fletchingtable" }
fletchingtable-neoforge = { id = "dev.kikugie.fletching-table.neoforge", version.ref = "fletchingtable" }